name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    name: Test on OTP ${{ matrix.otp_version }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        otp_version: [25, 26, 27]
        os: [ubuntu-latest]
      
    container:
      image: erlang:${{ matrix.otp_version }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        run: make

      - name: Test
        run: make test 
